version: "2"
services:
    waengine:
        build: .
        ports: 
            - "3094:3093"
        volumes:
            - .:/app/
            - ./node_modules/:/app/node_modules
            # - ~/.ssh:/root/.ssh
        command: 
            - /bin/sh
            - -c
            - |
                npm install
                nodemon index.js
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            API_URL: "host.docker.internal"
            HOST_DB: host.docker.internal
            USER_DB: user
            PASS_DB: test
            API_PORT: 80
            SENDMESSAGE_PATH: "/simpelapi/api/message"
            SCHEMA_DB: simpel2022
            PORT_DB: 33162